name:                hisp
version:             0.1.0.0
github:              "AdamsBenjamin/hisp"
license:             AGPL-3
author:              "Benjamin Adams"
maintainer:          "adams.benjamin@pm.me"
copyright:           "2023 Benjamin Adams"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AdamsBenjamin/hisp#readme>

dependencies:
- base >= 4.7 && < 5
- parsec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
  #- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hisp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hisp

tests:
  hisp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hisp
    - tasty >= 1.2.2 && < 1.6
    - HUnit >= 1.6.2.0
    - smallcheck
    - tasty-hunit
    - tasty-smallcheck
    - tasty-quickcheck
